Dynamic popup
Lul-Abdifan/Mobile_Portofolio pull request #11
Opened 2022-10-19 21:22 UTC by Lul-Abdifan

This milestone project includes:-
-Use javascript array to store objects
-Update to dynamically generated cards for mobile version
-Update to dynamically generated cards for desktop version
-Add blur effect for popup background
-Fix eslint error

2022-10-19 22:26 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Lul-Abdifan, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors. ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [x] Your work section should be all refactored and created dynamically with Javascript. You left 2 projects hard-coded. Please make those projects dynamically created with JS as you did with the others projects.
- [x] The second project you added is the hover version of the project card in the desktop version. When the user hovers, the project card should change to that appearance and the 'See Project' button should appear so the user can open the popup window. Kindly add that feature so the user can see the popup of the respective project. There is no way the user can access the popup window in the desktop version of your version.
-Your desktop version:
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/61919617/196815504-7e8ed3dc-eef9-4e7f-8090-1d1bd09befbb.png">


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-19 22:26 UTC, leonardodiasb commented on index.html
>                 <p>A daily selection of privately personalized reads; no accounts or sign-ups
- [ ] Please remove commented code. This makes your code look messy.

2022-10-19 22:26 UTC, leonardodiasb commented on index.html
>           <div class="cards card4" >
- [ ] Please remove commented code. This makes your code look messy.

2022-10-19 22:26 UTC, leonardodiasb commented on index.html
>              <h3 class="cards-header">Profesional Art <br>Printing Data</h3>
- [ ] Please remove commented code. This makes your code look messy.

2022-10-19 22:26 UTC, leonardodiasb commented on index.html
>                  <h3 class="cards-header">Profesional Art <br>Printing Data</h3>
- [ ] Please remove commented code. This makes your code look messy.

2022-10-19 22:26 UTC, leonardodiasb commented on index.html
>                  <h3 class="cards-header">Profesional Art <br>Printing Data</h3>
- [ ] Please remove commented code. This makes your code look messy.

2022-10-19 22:26 UTC, leonardodiasb commented on index.html
> +             </div> -->
- [ ] Please remove commented code. This makes your code look messy.

2022-10-19 22:26 UTC, leonardodiasb commented on script.js
> +      }
- [ ] Your function for rendering the popup window is rendering the same popup for all the projects. The popup window should display the information from the card that the user clicked. Kindly fix this issue so the user can get the correct information.

2022-10-20 20:44 UTC, Lul-Abdifan commented on index.html
>                 <p>A daily selection of privately personalized reads; no accounts or sign-ups
@leonardodiasb  Thank you for your feedback.I will do on my issues :+1: Happy Coding :smile:

2022-10-21 17:48 UTC, Lul-Abdifan commented
**Required changes are Done** :smile:
 - Make all cards refactored and created dynamically with Javascript.
 -Remove commented code
-Add two remaining cards to be generated dynamically as others
-Add a hover effect dynamically to get the See Project button for all cards
-Fix eslint error

2022-10-21 19:26 UTC, vickymarz approved these changes
Hi @Lul-Abdifan, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-21 19:58 UTC, merged

2022-10-21 19:59 UTC, Lul-Abdifan commented
> Hi @Lul-Abdifan,
> # heavy_check_mark Status: APPROVED trophy tada confetti_ball
> 
> You have done a great job on this project, keep it up +1 1st_place_medal. Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: congratulations! tada100star2
> ## Top highlight dart
> 
>     * The Pull Request is following the GitHub Flow white_check_mark
> 
>     * The PR title and description are professional and descriptive white_check_mark
> 
>     * The commit messages are meaningful white_check_mark
> 
>     * Linters are working properly white_check_mark
> 
> 
> ![](https://camo.githubusercontent.com/5d2ef7789f70f7829b4c278f18e77bc67da5412b06f77ddc5b0c1b0cff45702a/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966) [ ![68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://camo.githubusercontent.com/5d2ef7789f70f7829b4c278f18e77bc67da5412b06f77ddc5b0c1b0cff45702a/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966) ](https://camo.githubusercontent.com/5d2ef7789f70f7829b4c278f18e77bc67da5412b06f77ddc5b0c1b0cff45702a/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966) [ ](https://camo.githubusercontent.com/5d2ef7789f70f7829b4c278f18e77bc67da5412b06f77ddc5b0c1b0cff45702a/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966)
> ## Optional suggestions
> 
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-21 20:00 UTC, Lul-Abdifan commented
@[vickymarz](https://github.com/vickymarz) Thank you .:smile: Happy Coding.